apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
  namespace: donmoa-system
  labels:
    prometheus: donmoa
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - donmoa-dev
  selector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      honorLabels: false
