fullnameOverride: loki

deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2026-03-24"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: ""
      ruler: ""
      admin: ""
    s3:
      region: ""

  compactor:
    working_directory: /var/loki/compactor
    retention_enabled: true
    delete_request_store: s3

  limits_config:
    retention_period: 168h

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi
  persistence:
    enabled: true
    size: 20Gi
    storageClass: gp2

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

gateway:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false

minio:
  enabled: false

serviceAccount:
  create: true
  name: loki
  annotations: {}
