-- =========================================
-- Chat DB Schema (PostgreSQL)
-- =========================================

-- 1) Chat Rooms
CREATE TABLE IF NOT EXISTS chat_rooms (
    id BIGINT PRIMARY KEY, -- Snowflake ID
    room_key VARCHAR(190) NOT NULL,
    room_type VARCHAR(30) NOT NULL
        CHECK (room_type IN ('INQUIRY_1TO1', 'FUNDING_GROUP')),
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('OPEN', 'READ_ONLY', 'ARCHIVED')),
    item_id BIGINT,
    campaign_id BIGINT,
    seller_id BIGINT NOT NULL, -- user-service users.id (FK 미연결)
    title VARCHAR(200),
    read_only_at TIMESTAMP,
    read_only_reason VARCHAR(50)
        CHECK (read_only_reason IS NULL OR read_only_reason IN ('FUNDING_SUCCEEDED', 'FUNDING_FAILED', 'CAMPAIGN_ENDED', 'MANUAL_ARCHIVE')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_rooms_campaign_id
    ON chat_rooms (campaign_id);
CREATE INDEX IF NOT EXISTS idx_chat_rooms_seller_type_status
    ON chat_rooms (seller_id, room_type, status);

-- soft delete 호환 unique
CREATE UNIQUE INDEX IF NOT EXISTS uq_chat_rooms_room_key_active
    ON chat_rooms (room_key)
    WHERE deleted_at IS NULL;

-- 2) Chat Room Participants
CREATE TABLE IF NOT EXISTS chat_room_participants (
    id BIGINT PRIMARY KEY, -- Snowflake ID
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL, -- user-service users.id (FK 미연결)
    role VARCHAR(30) NOT NULL
        CHECK (role IN ('PARTICIPANT', 'SELLER_ADMIN', 'PLATFORM_ADMIN')),
    status VARCHAR(30) NOT NULL
        CHECK (status IN ('ACTIVE', 'LEFT_REFUNDED', 'REMOVED')),
    last_read_message_id BIGINT,
    joined_at TIMESTAMP NOT NULL,
    left_at TIMESTAMP,
    muted_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_chat_room_participants_room
        FOREIGN KEY (room_id) REFERENCES chat_rooms(id)
);

CREATE INDEX IF NOT EXISTS idx_chat_room_participants_user_status_room
    ON chat_room_participants (user_id, status, room_id);
CREATE INDEX IF NOT EXISTS idx_chat_room_participants_room_status
    ON chat_room_participants (room_id, status);

-- soft delete 호환 unique
CREATE UNIQUE INDEX IF NOT EXISTS uq_chat_room_participants_room_user_active
    ON chat_room_participants (room_id, user_id)
    WHERE deleted_at IS NULL;

-- 3) Chat Messages
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT PRIMARY KEY, -- Snowflake ID
    room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL, -- user-service users.id (FK 미연결)
    message_type VARCHAR(20) NOT NULL
        CHECK (message_type IN ('CHAT', 'NOTICE', 'SYSTEM')),
    client_message_id VARCHAR(100),
    content VARCHAR(4000) NOT NULL,
    content_sanitized VARCHAR(4000) NOT NULL,
    metadata JSONB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_chat_messages_room
        FOREIGN KEY (room_id) REFERENCES chat_rooms(id)
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_room_id_desc
    ON chat_messages (room_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_sender_created
    ON chat_messages (sender_id, created_at DESC);

-- soft delete + client message idempotency 호환 unique
CREATE UNIQUE INDEX IF NOT EXISTS uq_chat_messages_room_sender_client_active
    ON chat_messages (room_id, sender_id, client_message_id)
    WHERE client_message_id IS NOT NULL AND deleted_at IS NULL;

-- 4) Chat Audit Logs
CREATE TABLE IF NOT EXISTS chat_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT, -- user-service users.id (FK 미연결)
    room_id BIGINT,
    target_user_id BIGINT, -- user-service users.id (FK 미연결)
    event_type VARCHAR(60) NOT NULL,
    event_payload JSONB NOT NULL,
    correlation_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_audit_logs_event_created
    ON chat_audit_logs (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_audit_logs_room_created
    ON chat_audit_logs (room_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_audit_logs_actor_created
    ON chat_audit_logs (actor_id, created_at DESC);

-- 5) Chat Legal Holds
CREATE TABLE IF NOT EXISTS chat_legal_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL
        CHECK (target_type IN ('ROOM', 'MESSAGE', 'USER')),
    target_id VARCHAR(100) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL,
    created_by BIGINT NOT NULL, -- user-service users.id (FK 미연결)
    created_at TIMESTAMP NOT NULL,
    released_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_legal_holds_target_type_id
    ON chat_legal_holds (target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_chat_legal_holds_active_created
    ON chat_legal_holds (active, created_at);

-- active=true 기준 unique
CREATE UNIQUE INDEX IF NOT EXISTS uq_chat_legal_holds_active_target
    ON chat_legal_holds (target_type, target_id)
    WHERE active = TRUE;

-- 6) Processed Events (libs/config/kafka)
CREATE TABLE IF NOT EXISTS processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('PROCESSING', 'PROCESSED', 'FAILED')),
    processed_at TIMESTAMP,
    error_message TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_event_id
    ON processed_events (event_id);

-- 7) Dead Letter Messages (libs/config/kafka)
CREATE TABLE IF NOT EXISTS dead_letter_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(255) NOT NULL,
    partition_num INT,
    offset_num BIGINT,
    key_value VARCHAR(255),
    payload TEXT,
    error_message TEXT,
    event_id VARCHAR(255),
    event_type VARCHAR(255),
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('UNRESOLVED', 'RETRYING', 'RESOLVED')),
    retry_count INT NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dlm_status
    ON dead_letter_messages (status);
CREATE INDEX IF NOT EXISTS idx_dlm_topic_created
    ON dead_letter_messages (topic, created_at);
CREATE INDEX IF NOT EXISTS idx_dlm_event_id
    ON dead_letter_messages (event_id);

-- 8) Outbox (libs/event/outbox)
CREATE TABLE IF NOT EXISTS outbox_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('PENDING', 'SENDING', 'PUBLISHED', 'FAILED')),
    published_at TIMESTAMP,
    retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    error_message VARCHAR(500),
    correlation_id VARCHAR(255),
    causation_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_outbox_event_id
    ON outbox_messages (event_id);
CREATE INDEX IF NOT EXISTS idx_outbox_status_created
    ON outbox_messages (status, created_at);
CREATE INDEX IF NOT EXISTS idx_outbox_status_updated
    ON outbox_messages (status, updated_at);
CREATE INDEX IF NOT EXISTS idx_outbox_aggregate
    ON outbox_messages (aggregate_type, aggregate_id);
