{{- if and .Values.externalSecret.enabled .Values.secretEnv }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "spring-service.fullname" . }}
  labels:
    {{- include "spring-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "spring-service.secretName" . }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy }}
  data:
    {{- range $key, $value := .Values.secretEnv }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value.remoteRef | quote }}
        {{- if $value.property }}
        property: {{ $value.property | quote }}
        {{- end }}
    {{- end }}
{{- end }}
