dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation(platform("software.amazon.awssdk:bom:2.31.77"))
    implementation("software.amazon.awssdk:sqs")
    implementation("software.amazon.awssdk:sts")

    implementation(project(":libs:core:exception"))
    implementation(project(":libs:core:pagination"))
    implementation(project(":libs:api:response"))
    implementation(project(":libs:api:exception-handler"))
    implementation(project(":libs:data:entity"))
    implementation(project(":libs:config:kafka"))
    implementation(project(":libs:config:webclient"))
    implementation(project(":libs:event:consumer"))
    implementation(project(":libs:event:domain"))
    implementation(project(":libs:event:inbox"))
    implementation(project(":libs:event:outbox"))
    implementation(project(":libs:openapi:config"))
    implementation(project(":libs:security:security-starter"))

    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

    runtimeOnly("org.postgresql:postgresql")
    testRuntimeOnly("com.h2database:h2")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}
