name: Task
description: 개발 작업
title: "[TASK] "
labels: ["task"]
body:
  - type: input
    id: story
    attributes:
      label: 상위 Story
      placeholder: "#456"

  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      placeholder: User 엔티티 구현
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      options:
        - label: 코드 작성
        - label: 테스트 작성
        - label: 문서 업데이트