fullnameOverride: funding-service

image:
  repository: 682405977339.dkr.ecr.ap-northeast-2.amazonaws.com/donmoa-dev-funding-service
  tag: latest

service:
  port: 8086

container:
  port: 8086

env:
  SERVER_PORT: "8086"
  SPRING_PROFILES_ACTIVE: develop
  DB_URL: jdbc:postgresql://donmoa-dev-aurora.cluster-cfw84sg260sa.ap-northeast-2.rds.amazonaws.com:5432/funding_db
  APP_DATASOURCE_READ_URL: jdbc:postgresql://donmoa-dev-aurora.cluster-ro-cfw84sg260sa.ap-northeast-2.rds.amazonaws.com:5432/funding_db
  DB_USERNAME: postgres
  APP_DATASOURCE_READ_USERNAME: postgres
  APP_DATASOURCE_READ_WRITE_ROUTING_ENABLED: "true"
  REDIS_HOST: donmoa-dev-redis.awmnbx.ng.0001.apn2.cache.amazonaws.com
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: 10.30.130.193:9092
  SPRING_KAFKA_LISTENER_AUTO_STARTUP: "false"
  STOCK_SERVICE_URL: http://stock-service:8085
  APP_GATEWAY_SECURITY_ENABLED: "true"
  APP_GATEWAY_SECURITY_GATEWAY_AUTH_ENABLED: "true"
  APP_GATEWAY_SECURITY_INTERNAL_AUTH_HEADER: X-Gateway-Auth
  APP_GATEWAY_SECURITY_USER_ID_HEADER: X-User-Id

secretEnv:
  DB_PASSWORD:
    remoteRef: donmoa/dev/funding-db
    property: password
  APP_SECURITY_CONTEXT_SIGNING_KEY:
    remoteRef: donmoa/dev/common
    property: APP_SECURITY_CONTEXT_SIGNING_KEY
  APP_GATEWAY_SECURITY_INTERNAL_AUTH_TOKEN:
    remoteRef: donmoa/dev/common
    property: APP_GATEWAY_SECURITY_INTERNAL_AUTH_TOKEN
