fullnameOverride: store-query-service

image:
  repository: 682405977339.dkr.ecr.ap-northeast-2.amazonaws.com/donmoa-dev-store-query-service
  tag: latest

service:
  port: 8091

container:
  port: 8091

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

env:
  SERVER_PORT: "8091"
  SPRING_PROFILES_ACTIVE: develop
  JPA_DDL_AUTO: none
  DB_URL: jdbc:postgresql://donmoa-dev-aurora.cluster-cfw84sg260sa.ap-northeast-2.rds.amazonaws.com:5432/store_query_db
  DB_USERNAME: postgres
  REDIS_HOST: donmoa-dev-redis.awmnbx.ng.0001.apn2.cache.amazonaws.com
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: 10.30.130.193:9092
  MEDIA_SERVICE_URL: http://media-api:8094
  PRODUCT_SERVICE_URL: http://product-service:8084
  PROFILE_SERVICE_URL: http://profile-service:8071
  STORE_SERVICE_URL: http://store-service:8072
  APP_GATEWAY_SECURITY_ENABLED: "true"
  APP_GATEWAY_SECURITY_GATEWAY_AUTH_ENABLED: "false"
  APP_GATEWAY_SECURITY_INTERNAL_AUTH_HEADER: X-Gateway-Auth
  APP_GATEWAY_SECURITY_USER_ID_HEADER: X-User-Id
  APP_SECURITY_CONTEXT_MAX_AGE_MILLIS: "300000"

secretEnv:
  DB_PASSWORD:
    remoteRef: donmoa/dev/store-query-db
    property: password
  APP_SECURITY_CONTEXT_SIGNING_KEY:
    remoteRef: donmoa/dev/common
    property: APP_SECURITY_CONTEXT_SIGNING_KEY
  APP_GATEWAY_SECURITY_INTERNAL_AUTH_TOKEN:
    remoteRef: donmoa/dev/common
    property: APP_GATEWAY_SECURITY_INTERNAL_AUTH_TOKEN
