fullnameOverride: store-service

image:
  repository: 682405977339.dkr.ecr.ap-northeast-2.amazonaws.com/donmoa-dev-store-service
  tag: latest

service:
  port: 8072

container:
  port: 8072

env:
  SERVER_PORT: "8072"
  SPRING_PROFILES_ACTIVE: develop
  SPRING_DATASOURCE_URL: jdbc:postgresql://donmoa-dev-aurora.cluster-cfw84sg260sa.ap-northeast-2.rds.amazonaws.com:5432/store_db
  DB_USERNAME: postgres
  REDIS_HOST: donmoa-dev-redis.awmnbx.ng.0001.apn2.cache.amazonaws.com
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: 10.30.130.193:9092
  APP_SERVICE_MEDIA_URL: http://media-api:8094

secretEnv:
  DB_PASSWORD:
    remoteRef: donmoa/dev/store-db
    property: password
