CREATE TABLE IF NOT EXISTS store_read_models (
    store_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_name VARCHAR(120) NOT NULL,
    owner_nickname VARCHAR(100),
    owner_profile_image_url VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    description TEXT,
    default_address VARCHAR(400),
    default_address_type VARCHAR(30),
    primary_contact_value VARCHAR(100),
    primary_contact_type VARCHAR(30),
    thumbnail_media_id BIGINT,
    thumbnail_url VARCHAR(500),
    thumbnail_sort_order INTEGER,
    gallery_count INTEGER NOT NULL DEFAULT 0,
    active_item_count INTEGER NOT NULL DEFAULT 0,
    latest_item_updated_at TIMESTAMP,
    search_text TEXT,
    search_tsv TSVECTOR GENERATED ALWAYS AS (
        to_tsvector(
            'simple',
            trim(
                BOTH ' ' FROM
                coalesce(store_name, '') || ' ' ||
                coalesce(owner_nickname, '') || ' ' ||
                coalesce(search_text, '')
            )
        )
    ) STORED,
    source_created_at TIMESTAMP NOT NULL,
    source_updated_at TIMESTAMP NOT NULL,
    projected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP,
    CONSTRAINT chk_store_query_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT chk_store_query_address_type
        CHECK (default_address_type IS NULL OR default_address_type IN ('MAIN', 'PICKUP', 'RETURN', 'WAREHOUSE')),
    CONSTRAINT chk_store_query_contact_type
        CHECK (primary_contact_type IS NULL OR primary_contact_type IN ('PHONE', 'EMAIL'))
);

CREATE INDEX IF NOT EXISTS idx_store_read_models_status_updated
    ON store_read_models(status, source_updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_store_read_models_user_status_updated
    ON store_read_models(user_id, status, source_updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_store_read_models_search_tsv
    ON store_read_models
    USING GIN(search_tsv);

CREATE TABLE IF NOT EXISTS store_read_images (
    store_read_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    image_type VARCHAR(30) NOT NULL,
    media_id BIGINT NOT NULL,
    media_url VARCHAR(500),
    sort_order INTEGER NOT NULL,
    source_updated_at TIMESTAMP NOT NULL,
    projected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP,
    CONSTRAINT chk_store_read_images_type
        CHECK (image_type IN ('THUMBNAIL', 'GALLERY'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_store_read_images_store_media_active
    ON store_read_images(store_id, media_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_store_read_images_store_type_sort_active
    ON store_read_images(store_id, image_type, sort_order)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_store_read_images_store_sort
    ON store_read_images(store_id, image_type, sort_order);

CREATE TABLE IF NOT EXISTS store_read_items (
    item_id BIGINT PRIMARY KEY,
    store_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    price BIGINT NOT NULL,
    item_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    thumbnail_media_id BIGINT,
    thumbnail_url VARCHAR(500),
    source_updated_at TIMESTAMP NOT NULL,
    projected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_store_read_items_store_status_updated
    ON store_read_items(store_id, status, source_updated_at DESC);

CREATE TABLE IF NOT EXISTS store_rebuild_jobs (
    job_id BIGINT PRIMARY KEY,
    scope_type VARCHAR(30) NOT NULL,
    scope_key VARCHAR(100),
    status VARCHAR(30) NOT NULL,
    processed_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP,
    CONSTRAINT chk_store_rebuild_scope_type
        CHECK (scope_type IN ('STORE_ID', 'FULL')),
    CONSTRAINT chk_store_rebuild_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_store_rebuild_jobs_status_created
    ON store_rebuild_jobs(status, created_at DESC);
